apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  rules:
  - host: ${INGRESS_HOST}
    http:
      paths:
      - backend:
          service:
            name: webserver
            port:
              number: 8080
        path: /
        pathType: Prefix
